/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: flex-scale-mg-on.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _FLEX_SCALE_MG_ON_H_
#define _FLEX_SCALE_MG_ON_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef fsmgon__ns
#define fsmgon__ns 984017254
#define fsmgon__ns_id "http://flex-scale-project.eu/yang/flex-scale-mg-on"
#define fsmgon__ns_uri "http://flex-scale-project.eu/yang/flex-scale-mg-on"
#endif

#define fsmgon_port 10387472
#define fsmgon_MODE_THRESHOLD 0
#define fsmgon_ase_injection_mode 104663193
#define fsmgon_distribution 2032111206
#define fsmgon_index 827593980
#define fsmgon_name 1998270519
#define fsmgon_PRESENT 0
#define fsmgon_optical_bands 120585952
#define fsmgon_media_channels 521934610
#define fsmgon_optical_band 1173084308
#define fsmgon_config 2105663071
#define fsmgon_attenuation_control_mode 440330125
#define fsmgon_lower_frequency 297729851
#define fsmgon_DOWN 1
#define fsmgon_ase_injection_delta 2042047496
#define fsmgon_state 630973766
#define fsmgon_fibers 1790831125
#define fsmgon_admin_status 2104862928
#define fsmgon_NOT_PRESENT 1
#define fsmgon_optical_band_parent 1808487340
#define fsmgon_super_channel 1097338244
#define fsmgon_ase_injection_threshold 1092971224
#define fsmgon_wavelength_router 708507270
#define fsmgon_fiber_parent 654554990
#define fsmgon_channel 1372178362
#define fsmgon_port_name 771740271
#define fsmgon_MODE_DELTA 1
#define fsmgon_upper_frequency 2069940695
#define fsmgon_ase_status 1995125829
#define fsmgon_dest 1478643067
#define fsmgon_source 1141829056
#define fsmgon_spectrum_power_profile 1514396589
#define fsmgon_target_power 2112504380
#define fsmgon_ase_control_mode 177547951
#define fsmgon_port_spectrum_power_profiles 2042948932
#define fsmgon_fiber 15811569
#define fsmgon_UP 0
#define fsmgon_oper_status 1906453952
#define fsmgon_super_channel_parent 947631100

#ifdef __cplusplus
}
#endif

#endif
