/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-platform.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_PLATFORM_H_
#define _OPENCONFIG_PLATFORM_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_platform__ns
#define oc_platform__ns 748738173
#define oc_platform__ns_id "http://openconfig.net/yang/platform"
#define oc_platform__ns_uri "http://openconfig.net/yang/platform"
#endif

#define oc_platform_last_switchover_time 1406907417
#define oc_platform_completion_timeout_errors 663218889
#define oc_platform_used 1877002374
#define oc_platform_hdr_log_overflow_errors 1976644895
#define oc_platform_hardware_version 475247789
#define oc_platform_allocated_power 781373945
#define oc_platform_software_version 909128828
#define oc_platform_port 10387472
#define oc_platform_bad_tlp_errors 406320523
#define oc_platform_clei_code 140121519
#define oc_platform_mfg_name 1230757718
#define oc_platform_replay_timeout_errors 372637873
#define oc_platform_details 817440806
#define oc_platform_available 162386130
#define oc_platform_serial_no 480270650
#define oc_platform_name 1998270519
#define oc_platform_flow_control_protocol_errors 381485326
#define oc_platform_last_high_watermark 675792752
#define oc_platform_mfg_date 919146291
#define oc_platform_ecrc_errors 1755361413
#define oc_platform_committed 560677250
#define oc_platform_redundant_role 1283540569
#define oc_platform_receiver_overflow_errors 881839304
#define oc_platform_temperature 362670904
#define oc_platform_max 2088175689
#define oc_platform_used_threshold_upper 1755201737
#define oc_platform_location 1827424758
#define oc_platform_pcie 1446523019
#define oc_platform_unexpected_completion_errors 1753729482
#define oc_platform_last_switchover_reason 1583578456
#define oc_platform_relay_rollover_errors 1689552783
#define oc_platform_software_module 126935385
#define oc_platform_storage 452237353
#define oc_platform_acs_violation_errors 294053096
#define oc_platform_utilization 1882370771
#define oc_platform_min 83205090
#define oc_platform_receiver_errors 622596643
#define oc_platform_internal_errors 597954823
#define oc_platform_controller_card 977618700
#define oc_platform_resource 269073225
#define oc_platform_config 2105663071
#define oc_platform_subcomponents 1378797355
#define oc_platform_empty 330887823
#define oc_platform_max_time 1093347309
#define oc_platform_fan 1957768428
#define oc_platform_malformed_tlp_errors 529157101
#define oc_platform_poisoned_tlp_errors 1492740420
#define oc_platform_instant 2051543381
#define oc_platform_id 1279252765
#define oc_platform_subcomponent 410071270
#define oc_platform_description 202559156
#define oc_platform_free 274122866
#define oc_platform_utilized 2041312965
#define oc_platform_chassis 247732213
#define oc_platform_atomic_op_blocked_errors 219499856
#define oc_platform_fatal_errors 248455979
#define oc_platform_removable 1668816400
#define oc_platform_base_mac_address 885792997
#define oc_platform_configurable 1116873706
#define oc_platform_property 1802560321
#define oc_platform_interval 559952988
#define oc_platform_min_time 1805904672
#define oc_platform_integrated_circuit 658274749
#define oc_platform_last_reboot_reason 1791037239
#define oc_platform_value 864367181
#define oc_platform_state 630973766
#define oc_platform_high_watermark 771808196
#define oc_platform_advisory_non_fatal_errors 226597816
#define oc_platform_total_errors 1540795785
#define oc_platform_used_threshold_upper_exceeded 1857117334
#define oc_platform_firmware_version 1588326193
#define oc_platform_switchover_ready 1051054290
#define oc_platform_last_reboot_time 1740039375
#define oc_platform_alarm_severity 1871511136
#define oc_platform_unsupported_request_errors 939925491
#define oc_platform_avg 2050512522
#define oc_platform_properties 1953873399
#define oc_platform_part_no 1487153423
#define oc_platform_power_supply 1094968203
#define oc_platform_surprise_down_errors 173036853
#define oc_platform_parent 1504790702
#define oc_platform_fabric 76530483
#define oc_platform_bad_dllp_errors 1269509536
#define oc_platform_blocked_tlp_errors 2082725995
#define oc_platform_completion_abort_errors 963920551
#define oc_platform_cpu 1825182739
#define oc_platform_trigger 1458637089
#define oc_platform_memory 1156186237
#define oc_platform_alarm_threshold 27572169
#define oc_platform_max_limit 418580993
#define oc_platform_used_power 844379205
#define oc_platform_type 2040883914
#define oc_platform_correctable_errors 326462621
#define oc_platform_non_fatal_errors 1108105202
#define oc_platform_resources 1786797255
#define oc_platform_components 962606743
#define oc_platform_undefined_errors 2008913757
#define oc_platform_backplane 1637824912
#define oc_platform_component 1543026623
#define oc_platform_oper_status 1906453952
#define oc_platform_data_link_errors 1618380219
#define oc_platform_tlp_prefix_blocked_errors 1130721945
#define oc_platform_used_threshold_upper_clear 1993026272
#define oc_platform_alarm_status 1979041785

#ifdef __cplusplus
}
#endif

#endif
