/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-wavelength-router.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_WAVELENGTH_ROUTER_H_
#define _OPENCONFIG_WAVELENGTH_ROUTER_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_wave_router__ns
#define oc_wave_router__ns 342841198
#define oc_wave_router__ns_id "http://openconfig.net/yang/wavelength-router"
#define oc_wave_router__ns_uri "http://openconfig.net/yang/wavelength-router"
#endif

#define oc_wave_router_port 10387472
#define oc_wave_router_MODE_THRESHOLD 0
#define oc_wave_router_ase_injection_mode 104663193
#define oc_wave_router_AUTO_ASE_FAILURE_AND_RESTORE 2116345897
#define oc_wave_router_distribution 2032111206
#define oc_wave_router_index 827593980
#define oc_wave_router_AUTO_ASE_ON_FAILURE 1297791541
#define oc_wave_router_name 1998270519
#define oc_wave_router_ASE_CONTROL_MODE 1802449693
#define oc_wave_router_PRESENT 0
#define oc_wave_router_ASE_DISABLED 2002019498
#define oc_wave_router_ATTENUATION_CONTROL_MODE 1184613372
#define oc_wave_router_media_channels 521934610
#define oc_wave_router_config 2105663071
#define oc_wave_router_attenuation_control_mode 440330125
#define oc_wave_router_lower_frequency 297729851
#define oc_wave_router_DOWN 1
#define oc_wave_router_ase_injection_delta 2042047496
#define oc_wave_router_state 630973766
#define oc_wave_router_ATTENUATION_FIXED_LOSS 1467347203
#define oc_wave_router_admin_status 2104862928
#define oc_wave_router_NOT_PRESENT 1
#define oc_wave_router_super_channel 1097338244
#define oc_wave_router_wavelength_router 708507270
#define oc_wave_router_ase_injection_threshold 1092971224
#define oc_wave_router_channel 1372178362
#define oc_wave_router_port_name 771740271
#define oc_wave_router_MODE_DELTA 1
#define oc_wave_router_upper_frequency 2069940695
#define oc_wave_router_ATTENUATION_DYNAMIC_LOSS_DAMPED 1269481777
#define oc_wave_router_ase_status 1995125829
#define oc_wave_router_ATTENUATION_DYNAMIC_LOSS 164745702
#define oc_wave_router_dest 1478643067
#define oc_wave_router_source 1141829056
#define oc_wave_router_spectrum_power_profile 1514396589
#define oc_wave_router_target_power 2112504380
#define oc_wave_router_ase_control_mode 177547951
#define oc_wave_router_port_spectrum_power_profiles 2042948932
#define oc_wave_router_UP 0
#define oc_wave_router_oper_status 1906453952
#define oc_wave_router_super_channel_parent 947631100
#define oc_wave_router_ASE_ENABLED 973087157

#ifdef __cplusplus
}
#endif

#endif
