/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-platform-port.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_PLATFORM_PORT_H_
#define _OPENCONFIG_PLATFORM_PORT_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_port__ns
#define oc_port__ns 712718082
#define oc_port__ns_id "http://openconfig.net/yang/platform/port"
#define oc_port__ns_uri "http://openconfig.net/yang/platform/port"
#endif

#define oc_port_hardware_port 2121310890
#define oc_port_group 1540685982
#define oc_port_breakout_mode 429492013
#define oc_port_num_breakouts 872287550
#define oc_port_index 827593980
#define oc_port_groups 575296803
#define oc_port_config 2105663071
#define oc_port_state 630973766
#define oc_port_num_physical_channels 95222693
#define oc_port_breakout_speed 1595653044

#ifdef __cplusplus
}
#endif

#endif
