/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-ospfv2.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_OSPFV2_H_
#define _OPENCONFIG_OSPFV2_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_ospfv2__ns
#define oc_ospfv2__ns 1954233450
#define oc_ospfv2__ns_id "http://openconfig.net/yang/ospfv2"
#define oc_ospfv2__ns_uri "http://openconfig.net/yang/ospfv2"
#endif

#define oc_ospfv2_NSSA_EXTERNAL 7
#define oc_ospfv2_TYPE_1 0
#define oc_ospfv2_EXPONENTIAL_BACKOFF 1
#define oc_ospfv2_INTRA_AREA 1
#define oc_ospfv2_SOFTWARE_RESTART 1
#define oc_ospfv2_CONTROL_PROCESSOR_SWITCH 3
#define oc_ospfv2_AREA 1
#define oc_ospfv2_RFC1583_COMPATIBLE 0
#define oc_ospfv2_SOFTWARE_RELOAD_UPGRADE 2
#define oc_ospfv2_AS 2
#define oc_ospfv2_LINEAR_BACKOFF 0
#define oc_ospfv2_LOCAL 0
#define oc_ospfv2_INTER_AREA 3
#define oc_ospfv2_RFC2328_COMPATIBLE 1
#define oc_ospfv2_AS_EXTERNAL 5
#define oc_ospfv2_POINT_TO_POINT 0
#define oc_ospfv2_MULTI_ACCESS 1
#define oc_ospfv2_GLOBAL 1
#define oc_ospfv2_ABSOLUTE 0
#define oc_ospfv2_LINK 0
#define oc_ospfv2_UNSPECIFIED 0
#define oc_ospfv2_TYPE_2 1
#define oc_ospfv2_IPV4_UNICAST 0
#define oc_ospfv2_INDEX 1

#ifdef __cplusplus
}
#endif

#endif
