/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-network-instance-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_NETWORK_INSTANCE_TYPES_H_
#define _OPENCONFIG_NETWORK_INSTANCE_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_ni_types__ns
#define oc_ni_types__ns 2050400518
#define oc_ni_types__ns_id "http://openconfig.net/yang/network-instance-types"
#define oc_ni_types__ns_uri "http://openconfig.net/yang/network-instance-types"
#endif

#define oc_ni_types_L2L3 549903540
#define oc_ni_types_SIGNALLING_PROTOCOL 1324016391
#define oc_ni_types_LABEL_ALLOCATION_MODE 729169488
#define oc_ni_types_NETWORK_INSTANCE_TYPE 691911598
#define oc_ni_types_VXLAN 1449468224
#define oc_ni_types_PER_PREFIX 932560854
#define oc_ni_types_MPLS 2067937967
#define oc_ni_types_PER_NEXTHOP 1781188095
#define oc_ni_types_LOCAL 460621875
#define oc_ni_types_L2VSI 54139560
#define oc_ni_types_ENCAPSULATION 1893057283
#define oc_ni_types_REMOTE 1111950581
#define oc_ni_types_DEFAULT_INSTANCE 899602892
#define oc_ni_types_LDP 1944089980
#define oc_ni_types_L3VRF 1684502484
#define oc_ni_types_ENDPOINT_TYPE 97140199
#define oc_ni_types_L2P2P 1871119045
#define oc_ni_types_BGP_EVPN 17969827
#define oc_ni_types_INSTANCE_LABEL 1331221488
#define oc_ni_types_BGP_VPLS 178280769

#ifdef __cplusplus
}
#endif

#endif
