/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-mpls-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_MPLS_TYPES_H_
#define _OPENCONFIG_MPLS_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_mplst__ns
#define oc_mplst__ns 2060725838
#define oc_mplst__ns_id "http://openconfig.net/yang/mpls-types"
#define oc_mplst__ns_uri "http://openconfig.net/yang/mpls-types"
#endif

#define oc_mplst_TE_METRIC 574407998
#define oc_mplst_PATH_SETUP_PROTOCOL 835244345
#define oc_mplst_PWE_ETHERNET_RAW_MODE 1007406657
#define oc_mplst_ADMIN_DOWN 1148257599
#define oc_mplst_PATH_COMPUTATION_METHOD 234592098
#define oc_mplst_NO_LABEL 8
#define oc_mplst_PSEUDOWIRE_ENCAPSULATION 1463326732
#define oc_mplst_PROTECTION_TYPE 2136664093
#define oc_mplst_HOP_COUNT 811831673
#define oc_mplst_MP2MP 2
#define oc_mplst_LINK_PROTECTION_REQUIRED 988539287
#define oc_mplst_PATH_SETUP_LDP 611886302
#define oc_mplst_RSVP_AUTH_MD5 1777078169
#define oc_mplst_EXTERNALLY_QUERIED 337536599
#define oc_mplst_IPV6_EXPLICIT_NULL 2
#define oc_mplst_NULL_LABEL_TYPE 868813196
#define oc_mplst_LSP_METRIC_ABSOLUTE 1134021406
#define oc_mplst_INGRESS 29620309
#define oc_mplst_ROUTER_ALERT 1
#define oc_mplst_PATH_SETUP_SR 1477637560
#define oc_mplst_LSP_METRIC_INHERITED 1014009769
#define oc_mplst_LINK_NODE_PROTECTION_REQUESTED 1254001062
#define oc_mplst_LSP_METRIC_TYPE 201394383
#define oc_mplst_TUNNEL_TYPE 1375921361
#define oc_mplst_LSP_METRIC_RELATIVE 1300520727
#define oc_mplst_TRANSIT 452334754
#define oc_mplst_EXPLICIT 1076787690
#define oc_mplst_DOWN 1781612810
#define oc_mplst_IPV4_EXPLICIT_NULL 0
#define oc_mplst_LSP_OPER_STATUS 1051818982
#define oc_mplst_UNPROTECTED 2079021224
#define oc_mplst_LOCALLY_COMPUTED 1293036582
#define oc_mplst_EGRESS 169325739
#define oc_mplst_IMPLICIT_NULL 3
#define oc_mplst_PATH_SETUP_RSVP 262926226
#define oc_mplst_PWE_ETHERNET_TAGGED_MODE 1559585420
#define oc_mplst_ADMIN_UP 576039285
#define oc_mplst_EXPLICITLY_DEFINED 668431949
#define oc_mplst_IGP_METRIC 197784630
#define oc_mplst_PATH_METRIC_TYPE 1097735656
#define oc_mplst_UP 82258393
#define oc_mplst_PATH_DELAY 385616499
#define oc_mplst_TUNNEL_ADMIN_STATUS 300623166
#define oc_mplst_ENTROPY_LABEL_INDICATOR 7
#define oc_mplst_IMPLICIT 47075559
#define oc_mplst_RSVP_AUTH_TYPE 1909696639
#define oc_mplst_LSP_ROLE 1098150761

#ifdef __cplusplus
}
#endif

#endif
