/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-bfd.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_BFD_H_
#define _OPENCONFIG_BFD_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_bfd__ns
#define oc_bfd__ns 2061158769
#define oc_bfd__ns_id "http://openconfig.net/yang/bfd"
#define oc_bfd__ns_uri "http://openconfig.net/yang/bfd"
#endif

#define oc_bfd_last_packet_transmitted 1121940878
#define oc_bfd_enabled 197426095
#define oc_bfd_subscribed_protocols 1406157166
#define oc_bfd_ECHO_FAILED 2
#define oc_bfd_NO_DIAGNOSTIC 0
#define oc_bfd_last_failure_time 2146776803
#define oc_bfd_remote_discriminator 1231281115
#define oc_bfd_transmitted_packets 2089984096
#define oc_bfd_peers 958391453
#define oc_bfd_detection_multiplier 1584191488
#define oc_bfd_up_transitions 649368090
#define oc_bfd_interface 221572658
#define oc_bfd_INIT 3
#define oc_bfd_REVERSE_CONCATENATED_PATH_DOWN 7
#define oc_bfd_DETECTION_TIMEOUT 1
#define oc_bfd_echo 954217248
#define oc_bfd_member_interface 1434228746
#define oc_bfd_interface_ref 952985348
#define oc_bfd_PATH_DOWN 4
#define oc_bfd_demand_mode_requested 753081880
#define oc_bfd_CONCATENATED_PATH_DOWN 5
#define oc_bfd_config 2105663071
#define oc_bfd_remote_control_plane_independent 1577008036
#define oc_bfd_peer 1450174230
#define oc_bfd_last_packet_received 132602702
#define oc_bfd_required_minimum_receive 747584394
#define oc_bfd_remote_diagnostic_code 102118665
#define oc_bfd_id 1279252765
#define oc_bfd_local_diagnostic_code 349342118
#define oc_bfd_DOWN 1
#define oc_bfd_subinterface 1294223328
#define oc_bfd_state 630973766
#define oc_bfd_enable_per_member_link 117254987
#define oc_bfd_session_state 113214794
#define oc_bfd_async 1368962940
#define oc_bfd_bfd 788285710
#define oc_bfd_local_discriminator 968074567
#define oc_bfd_remote_session_state 1414644266
#define oc_bfd_interfaces 321503962
#define oc_bfd_remote_minimum_receive_interval 740363723
#define oc_bfd_micro_bfd_session 1055177085
#define oc_bfd_local_address 856636202
#define oc_bfd_received_packets 458197719
#define oc_bfd_failure_transitions 272899228
#define oc_bfd_remote_address 829475023
#define oc_bfd_desired_minimum_tx_interval 1752975443
#define oc_bfd_UP 0
#define oc_bfd_remote_authentication_enabled 258181007
#define oc_bfd_micro_bfd_sessions 1052751491
#define oc_bfd_active 124277386
#define oc_bfd_FORWARDING_RESET 3

#ifdef __cplusplus
}
#endif

#endif
