/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-rib-bgp-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_RIB_BGP_TYPES_H_
#define _OPENCONFIG_RIB_BGP_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_bgprib_types__ns
#define oc_bgprib_types__ns 266928794
#define oc_bgprib_types__ns_id "http://openconfig.net/yang/rib/bgp-types"
#define oc_bgprib_types__ns_uri "http://openconfig.net/yang/rib/bgp-types"
#endif

#define oc_bgprib_types_SRTE_BINDING_SID 269858494
#define oc_bgprib_types_SRTE_POLICY_TUNNEL 1978555137
#define oc_bgprib_types_INVALID_ROUTE_REASON 746597251
#define oc_bgprib_types_NEXTHOP_COST_HIGHER 77979501
#define oc_bgprib_types_SRTE_SEGMENT_LIST_SEGMENT 1179967674
#define oc_bgprib_types_MED_HIGHER 229978588
#define oc_bgprib_types_TUNNEL_ENCAPSULATION_TYPE 921334966
#define oc_bgprib_types_SRTE_SEGMENT_LIST 316437334
#define oc_bgprib_types_BGP_NOT_SELECTED_BESTPATH 1332166396
#define oc_bgprib_types_INVALID_AS_LOOP 1123243151
#define oc_bgprib_types_INVALID_CLUSTER_LOOP 57263232
#define oc_bgprib_types_LOCAL_PREF_LOWER 182942030
#define oc_bgprib_types_TUNNEL_ENCAPSULATION_SUBTLV_TYPE 665619248
#define oc_bgprib_types_REJECTED_IMPORT_POLICY 1400155361
#define oc_bgprib_types_SRTE_PREFERENCE 1326398230
#define oc_bgprib_types_TUNNEL_REMOTE_ENDPOINT 751390676
#define oc_bgprib_types_PREFER_EXTERNAL 964932319
#define oc_bgprib_types_HIGHER_PEER_ADDRESS 1572276748
#define oc_bgprib_types_AS_PATH_LONGER 1223099127
#define oc_bgprib_types_HIGHER_ROUTER_ID 952572681
#define oc_bgprib_types_INVALID_ORIGINATOR 1735450243
#define oc_bgprib_types_TUNNEL_COLOR 1903881231
#define oc_bgprib_types_ORIGIN_TYPE_HIGHER 1179538394
#define oc_bgprib_types_BGP_NOT_SELECTED_POLICY 1471810501
#define oc_bgprib_types_SRTE_SEGMENT_LIST_WEIGHT 1847497617
#define oc_bgprib_types_INVALID_CONFED 1394621379
#define oc_bgprib_types_SRTE_SEGMENT_LIST_SUBTLV 727593094

#ifdef __cplusplus
}
#endif

#endif
