/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-bgp.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_BGP_H_
#define _OPENCONFIG_BGP_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_bgp__ns
#define oc_bgp__ns 846400537
#define oc_bgp__ns_id "http://openconfig.net/yang/bgp"
#define oc_bgp__ns_uri "http://openconfig.net/yang/bgp"
#endif

#define oc_bgp_received 945228780
#define oc_bgp_confederation 2023333591
#define oc_bgp_l3vpn_ipv4_unicast 279465777
#define oc_bgp_prefix 1408440115
#define oc_bgp_enabled 197426095
#define oc_bgp_messages 1588018753
#define oc_bgp_allow_multiple_as 221443886
#define oc_bgp_error_handling 142328321
#define oc_bgp_logging_options 481236423
#define oc_bgp_neighbors 1478644450
#define oc_bgp_sent 608300980
#define oc_bgp_l3vpn_ipv6_multicast 1787203191
#define oc_bgp_import_policy 843610784
#define oc_bgp_receive 716682309
#define oc_bgp_peer_as 542003455
#define oc_bgp_keepalive_interval 298740851
#define oc_bgp_ACTIVE 2
#define oc_bgp_tcp_mss 926457527
#define oc_bgp_external_route_distance 1937317739
#define oc_bgp_member_as 743407420
#define oc_bgp_srte_policy_ipv4 774242984
#define oc_bgp_afi_safis 996404437
#define oc_bgp_last_notification_error_subcode 1921417243
#define oc_bgp_dynamic_neighbor_prefix 2038074947
#define oc_bgp_received_pre_policy 1227644837
#define oc_bgp_apply_policy 1819569988
#define oc_bgp_ipv6_labeled_unicast 1979838607
#define oc_bgp_peer_restarting 1611254302
#define oc_bgp_enable_bfd 302087594
#define oc_bgp_as_path_options 1085027654
#define oc_bgp_last_prefix_limit_exceeded 1731622563
#define oc_bgp_route_selection_options 1632804184
#define oc_bgp_dynamic_neighbor_prefixes 645889134
#define oc_bgp_replace_peer_as 1183812002
#define oc_bgp_mode 575893728
#define oc_bgp_helper_only 303858949
#define oc_bgp_use_multiple_paths 150611756
#define oc_bgp_HELPER_ONLY 0
#define oc_bgp_route_reflector_client 1028338377
#define oc_bgp_enable_aigp 307909287
#define oc_bgp_supported_capabilities 293047685
#define oc_bgp_local_as 1447589626
#define oc_bgp_export_policy 927333633
#define oc_bgp_address_family 203507431
#define oc_bgp_installed 956363481
#define oc_bgp_default_route_distance 929178712
#define oc_bgp_remote_port 1738088052
#define oc_bgp_ESTABLISHED 5
#define oc_bgp_always_compare_med 179211405
#define oc_bgp_router_id 519485925
#define oc_bgp_dynamically_configured 1711067066
#define oc_bgp_multihop_ttl 345574799
#define oc_bgp_max_prefixes 1067963849
#define oc_bgp_send_community 223183420
#define oc_bgp_send_default_route 1062340939
#define oc_bgp_extended_next_hop_encoding 1780618879
#define oc_bgp_config 2105663071
#define oc_bgp_l3vpn_ipv4_multicast 281040541
#define oc_bgp_ignore_next_hop_igp_metric 1114435048
#define oc_bgp_connect_retry 861842190
#define oc_bgp_transport 514190987
#define oc_bgp_ipv4_labeled_unicast 140868754
#define oc_bgp_remove_private_as 965066671
#define oc_bgp_CONNECT 1
#define oc_bgp_prefix_limit_received 456951867
#define oc_bgp_description 202559156
#define oc_bgp_neighbor 81789621
#define oc_bgp_route_reflector 287035089
#define oc_bgp_log_neighbor_state_changes 1454003914
#define oc_bgp_mtu_discovery 1365118732
#define oc_bgp_ipv6_unicast 540616510
#define oc_bgp_ipv4_unicast 2018585830
#define oc_bgp_ebgp 2120040446
#define oc_bgp_advertise_inactive_routes 985696490
#define oc_bgp_l2vpn_evpn 1956112043
#define oc_bgp_total_paths 1567128751
#define oc_bgp_state 630973766
#define oc_bgp_local_restarting 556686850
#define oc_bgp_queues 1554919660
#define oc_bgp_bgp 555337807
#define oc_bgp_internal_route_distance 2086920284
#define oc_bgp_established_transitions 56680336
#define oc_bgp_last_established 1850038628
#define oc_bgp_prefix_limit_exceeded 54399290
#define oc_bgp_warning_threshold_pct 359329615
#define oc_bgp_stale_routes_time 1948094824
#define oc_bgp_ignore_as_path_length 14187052
#define oc_bgp_eligible_prefix_policy 1289911603
#define oc_bgp_session_state 113214794
#define oc_bgp_UPDATE 1123452143
#define oc_bgp_default_export_policy 1570998897
#define oc_bgp_last_notification_time 1374516872
#define oc_bgp_hold_time 204730640
#define oc_bgp_graceful_restart 298735851
#define oc_bgp_REMOTE_HELPER 2
#define oc_bgp_send_max 663865290
#define oc_bgp_treat_as_withdraw 1486450692
#define oc_bgp_OPENSENT 3
#define oc_bgp_NOTIFICATION 207681821
#define oc_bgp_default_import_policy 832483251
#define oc_bgp_route_flap_damping 1907200804
#define oc_bgp_OPENCONFIRM 4
#define oc_bgp_erroneous_update_messages 540667499
#define oc_bgp_afi_safi 1155227585
#define oc_bgp_minimum_advertisement_interval 1145123311
#define oc_bgp_add_paths 513350841
#define oc_bgp_ebgp_multihop 467962677
#define oc_bgp_l3vpn_ipv6_unicast 1177837375
#define oc_bgp_static 1504445999
#define oc_bgp_neighbor_if 403884867
#define oc_bgp_external_compare_router_id 1376118690
#define oc_bgp_prevent_teardown 572222552
#define oc_bgp_neighbor_port 178750302
#define oc_bgp_as 388223143
#define oc_bgp_bgp_instance 1579720599
#define oc_bgp_neighbor_address 1654322417
#define oc_bgp_l2vpn_vpls 1942955774
#define oc_bgp_route_reflector_cluster_id 70548336
#define oc_bgp_input 1427240772
#define oc_bgp_local_address 856636202
#define oc_bgp_local_port 560832355
#define oc_bgp_global 1112611080
#define oc_bgp_negotiated_hold_time 1275632634
#define oc_bgp_identifier 1002883111
#define oc_bgp_prefix_limit 556121524
#define oc_bgp_prefixes 1405994391
#define oc_bgp_timers 1742815315
#define oc_bgp_srte_policy_ipv6 512870036
#define oc_bgp_afi_safi_name 624387796
#define oc_bgp_disable_peer_as_filter 896624674
#define oc_bgp_remote_address 829475023
#define oc_bgp_send 1238787519
#define oc_bgp_last_notification_error_code 1831694112
#define oc_bgp_output 171341581
#define oc_bgp_IDLE 0
#define oc_bgp_peer_restart_time 2080463227
#define oc_bgp_peer_type 1801912036
#define oc_bgp_connected 1024392365
#define oc_bgp_allow_own_as 1596921337
#define oc_bgp_restart_time 493265707
#define oc_bgp_passive_mode 930513602
#define oc_bgp_auth_password 1498679463
#define oc_bgp_active 124277386
#define oc_bgp_BILATERAL 1
#define oc_bgp_total_prefixes 2121610949
#define oc_bgp_advertised 953526844

#ifdef __cplusplus
}
#endif

#endif
