/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-segment-routing-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_SEGMENT_ROUTING_TYPES_H_
#define _OPENCONFIG_SEGMENT_ROUTING_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_srt__ns
#define oc_srt__ns 2010618222
#define oc_srt__ns_id "http://openconfig.net/yang/segment-routing-types"
#define oc_srt__ns_uri "http://openconfig.net/yang/segment-routing-types"
#endif

#define oc_srt_BGP 20
#define oc_srt_VERIFICATION_FAIL 4
#define oc_srt_FIRST_SID_UNRESOLVABLE 2
#define oc_srt_MPLS 0
#define oc_srt_PCEP 10
#define oc_srt_ZERO_WEIGHT 1
#define oc_srt_EMPTY_SL 0
#define oc_srt_PUSH_IPV46_EXPLICIT_NULL 2
#define oc_srt_IPV6 1
#define oc_srt_PUSH_IPV6_EXPLICIT_NULL 1
#define oc_srt_OTHER_SID_UNRESOLVABLE 3
#define oc_srt_CONFIG 30
#define oc_srt_NO_EXPLICIT_NULL 3
#define oc_srt_PUSH_IPV4_EXPLICIT_NULL 0

#ifdef __cplusplus
}
#endif

#endif
