/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-rib-bgp.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_RIB_BGP_H_
#define _OPENCONFIG_RIB_BGP_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_rib_bgp__ns
#define oc_rib_bgp__ns 1347194096
#define oc_rib_bgp__ns_id "http://openconfig.net/yang/rib/bgp"
#define oc_rib_bgp__ns_uri "http://openconfig.net/yang/rib/bgp"
#endif

#define oc_rib_bgp_IPV6_LOCAL_REMOTE_ADDR 8
#define oc_rib_bgp_IPV6_NODE_ADDRESS 4
#define oc_rib_bgp_IPV4_LOCAL_REMOTE_ADDR 6
#define oc_rib_bgp_IPV4_LOCAL_INTF_ID 5
#define oc_rib_bgp_IPV6_LOCAL_INTF_ID 7
#define oc_rib_bgp_IPV4_NODE_ADDRESS 3
#define oc_rib_bgp_IPV6_SID 2
#define oc_rib_bgp_MPLS_SID 1

#ifdef __cplusplus
}
#endif

#endif
