/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-lldp.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_LLDP_H_
#define _OPENCONFIG_LLDP_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_lldp__ns
#define oc_lldp__ns 2126959692
#define oc_lldp__ns_id "http://openconfig.net/yang/lldp"
#define oc_lldp__ns_uri "http://openconfig.net/yang/lldp"
#endif

#define oc_lldp_enabled 197426095
#define oc_lldp_hello_timer 1869518339
#define oc_lldp_neighbors 1478644450
#define oc_lldp_oui_subtype 960442680
#define oc_lldp_system_description 1651773485
#define oc_lldp_oui 169238003
#define oc_lldp_system_name 1975516496
#define oc_lldp_port_description 1466459667
#define oc_lldp_tlv_unknown 546776942
#define oc_lldp_name 1998270519
#define oc_lldp_management_address 613978086
#define oc_lldp_interface 221572658
#define oc_lldp_tlv 1250745731
#define oc_lldp_port_id_type 1294387739
#define oc_lldp_entries_aged_out 818798602
#define oc_lldp_config 2105663071
#define oc_lldp_lldp 830250803
#define oc_lldp_id 1279252765
#define oc_lldp_frame_error_in 511909285
#define oc_lldp_frame_error_out 1736170451
#define oc_lldp_neighbor 81789621
#define oc_lldp_last_update 498080631
#define oc_lldp_frame_out 899192982
#define oc_lldp_management_address_type 1070023607
#define oc_lldp_value 864367181
#define oc_lldp_state 630973766
#define oc_lldp_chassis_id_type 2064781464
#define oc_lldp_counters 1327053922
#define oc_lldp_suppress_tlv_advertisement 1552375923
#define oc_lldp_frame_discard 1933515315
#define oc_lldp_custom_tlvs 1472881104
#define oc_lldp_last_clear 1168907511
#define oc_lldp_interfaces 321503962
#define oc_lldp_tlv_accepted 1856541892
#define oc_lldp_age 304093784
#define oc_lldp_capabilities 1381570067
#define oc_lldp_tlv_discard 75606479
#define oc_lldp_type 2040883914
#define oc_lldp_capability 1251322185
#define oc_lldp_port_id 411479338
#define oc_lldp_ttl 774234709
#define oc_lldp_chassis_id 1476535866
#define oc_lldp_frame_in 497567735

#ifdef __cplusplus
}
#endif

#endif
