/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-if-ip.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_IF_IP_H_
#define _OPENCONFIG_IF_IP_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_ip__ns
#define oc_ip__ns 1247422765
#define oc_ip__ns_id "http://openconfig.net/yang/interfaces/ip"
#define oc_ip__ns_uri "http://openconfig.net/yang/interfaces/ip"
#endif

#define oc_ip_out_pkts 335453834
#define oc_ip_enabled 197426095
#define oc_ip_DHCP 2
#define oc_ip_STALE 2
#define oc_ip_neighbors 1478644450
#define oc_ip_REMOTE_ONLY 1
#define oc_ip_DELAY 3
#define oc_ip_mtu 1751455506
#define oc_ip_origin 2002579816
#define oc_ip_PREFERRED 0
#define oc_ip_is_router 1891156201
#define oc_ip_out_forwarded_octets 1487514732
#define oc_ip_interface 221572658
#define oc_ip_proxy_arp 676928388
#define oc_ip_mode 575893728
#define oc_ip_in_pkts 1264605324
#define oc_ip_interface_ref 952985348
#define oc_ip_STATIC 1
#define oc_ip_TENTATIVE 5
#define oc_ip_INACCESSIBLE 3
#define oc_ip_config 2105663071
#define oc_ip_in_octets 1354763654
#define oc_ip_lifetime 92991035
#define oc_ip_UNKNOWN 4
#define oc_ip_router_advertisement 996372025
#define oc_ip_ip 1643785435
#define oc_ip_INVALID 2
#define oc_ip_unnumbered 1288780644
#define oc_ip_neighbor 81789621
#define oc_ip_ipv4 268057062
#define oc_ip_PROBE 4
#define oc_ip_out_octets 2123582464
#define oc_ip_subinterface 1294223328
#define oc_ip_interval 559952988
#define oc_ip_state 630973766
#define oc_ip_DUPLICATE 6
#define oc_ip_dup_addr_detect_transmits 53367116
#define oc_ip_ALL 2
#define oc_ip_OPTIMISTIC 7
#define oc_ip_ipv6 1228132394
#define oc_ip_OTHER 0
#define oc_ip_counters 1327053922
#define oc_ip_LINK_LAYER 3
#define oc_ip_dhcp_client 1259775382
#define oc_ip_address 1266954393
#define oc_ip_in_forwarded_octets 425114535
#define oc_ip_DEPRECATED 1
#define oc_ip_in_forwarded_pkts 1440015958
#define oc_ip_link_layer_address 2084100809
#define oc_ip_DYNAMIC 2
#define oc_ip_suppress 1746378947
#define oc_ip_in_error_pkts 1525691105
#define oc_ip_out_forwarded_pkts 1671788686
#define oc_ip_DISABLE 0
#define oc_ip_out_error_pkts 1259985273
#define oc_ip_status 1950810920
#define oc_ip_addresses 1825332052
#define oc_ip_neighbor_state 393193907
#define oc_ip_INCOMPLETE 0
#define oc_ip_out_discarded_pkts 2063997953
#define oc_ip_in_discarded_pkts 1037387075
#define oc_ip_RANDOM 4
#define oc_ip_prefix_length 524393771
#define oc_ip_REACHABLE 1

#ifdef __cplusplus
}
#endif

#endif
