/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-policy-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_POLICY_TYPES_H_
#define _OPENCONFIG_POLICY_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_pol_types__ns
#define oc_pol_types__ns 5273227
#define oc_pol_types__ns_id "http://openconfig.net/yang/policy-types"
#define oc_pol_types__ns_uri "http://openconfig.net/yang/policy-types"
#endif

#define oc_pol_types_BGP 346655972
#define oc_pol_types_PIM 1710011258
#define oc_pol_types_LOCAL 460621875
#define oc_pol_types_ANY 0
#define oc_pol_types_PCEP 696331841
#define oc_pol_types_ATTRIBUTE_EQ 382212571
#define oc_pol_types_ATTRIBUTE_LE 121645146
#define oc_pol_types_LOCAL_AGGREGATE 1483965019
#define oc_pol_types_OSPF 619009612
#define oc_pol_types_OSPF3 630371620
#define oc_pol_types_ATTRIBUTE_COMPARISON 1727192591
#define oc_pol_types_STATIC 977019608
#define oc_pol_types_GRIBI 901890394
#define oc_pol_types_DIRECTLY_CONNECTED 615714624
#define oc_pol_types_ATTRIBUTE_GE 1537951632
#define oc_pol_types_ISIS 574246373
#define oc_pol_types_ALL 1
#define oc_pol_types_INSTALL_PROTOCOL_TYPE 1846295931
#define oc_pol_types_IGMP 1678389166

#ifdef __cplusplus
}
#endif

#endif
