/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-evpn-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_EVPN_TYPES_H_
#define _OPENCONFIG_EVPN_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_evpn_types__ns
#define oc_evpn_types__ns 1098250130
#define oc_evpn_types__ns_id "http://openconfig.net/yang/evpn-types"
#define oc_evpn_types__ns_uri "http://openconfig.net/yang/evpn-types"
#endif

#define oc_evpn_types_TYPE_1_LACP_BASED 1
#define oc_evpn_types_EVPN_REDUNDANCY_MODE 1952232930
#define oc_evpn_types_TYPE_5_AS_BASED 5
#define oc_evpn_types_VXLAN 1
#define oc_evpn_types_NONE 0
#define oc_evpn_types_LOCAL 0
#define oc_evpn_types_MAC_VRF 1318653587
#define oc_evpn_types_EVPN_CAPABILITY 1841362908
#define oc_evpn_types_STATIC 0
#define oc_evpn_types_DATA_PLANE 1
#define oc_evpn_types_VLAN_BUNDLE 1372939797
#define oc_evpn_types_INVALID 2
#define oc_evpn_types_CONTROL_PLANE 0
#define oc_evpn_types_EVI 1958456747
#define oc_evpn_types_CONNECTED 2
#define oc_evpn_types_NVE 1299005861
#define oc_evpn_types_ALL_ACTIVE 1273543671
#define oc_evpn_types_TYPE_4_ROUTER_ID_BASED 4
#define oc_evpn_types_ALL 2
#define oc_evpn_types_TYPE_0_OPERATOR_CONFIGURED 0
#define oc_evpn_types_REMOTE 1
#define oc_evpn_types_TYPE_2_BRIDGE_PROTOCOL_BASED 2
#define oc_evpn_types_EVPN_TYPE 2134458162
#define oc_evpn_types_TYPE_3_MAC_BASED 3
#define oc_evpn_types_DYNAMIC 1
#define oc_evpn_types_SINGLE_ACTIVE 134677756
#define oc_evpn_types_VLAN_AWARE 1224275169
#define oc_evpn_types_VLAN_BASED 771125677
#define oc_evpn_types_IRB 1293421017
#define oc_evpn_types_IP_VRF 873762200

#ifdef __cplusplus
}
#endif

#endif
