/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-lldp-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_LLDP_TYPES_H_
#define _OPENCONFIG_LLDP_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_lldp_types__ns
#define oc_lldp_types__ns 2096380014
#define oc_lldp_types__ns_id "http://openconfig.net/yang/lldp/types"
#define oc_lldp_types__ns_uri "http://openconfig.net/yang/lldp/types"
#endif

#define oc_lldp_types_STATION_ONLY 1637537553
#define oc_lldp_types_PORT_DESCRIPTION 1817475244
#define oc_lldp_types_S_VLAN 631405204
#define oc_lldp_types_LOCAL 6
#define oc_lldp_types_LLDP_SYSTEM_CAPABILITY 1980778876
#define oc_lldp_types_LLDP_TLV 393189728
#define oc_lldp_types_WLAN_ACCESS_POINT 1380901949
#define oc_lldp_types_TELEPHONE 1567432922
#define oc_lldp_types_CHASSIS_ID 356369854
#define oc_lldp_types_SYSTEM_NAME 877909834
#define oc_lldp_types_AGENT_CIRCUIT_ID 5
#define oc_lldp_types_SYSTEM_CAPABILITIES 2040546183
#define oc_lldp_types_PORT_ID 659261922
#define oc_lldp_types_SYSTEM_DESCRIPTION 281620828
#define oc_lldp_types_OTHER 187383631
#define oc_lldp_types_DOCSIS_CABLE_DEVICE 1863222733
#define oc_lldp_types_TWO_PORT_MAC_RELAY 896164942
#define oc_lldp_types_ROUTER 399545655
#define oc_lldp_types_REPEATER 1691447740
#define oc_lldp_types_C_VLAN 842728206
#define oc_lldp_types_MAC_BRIDGE 138170127
#define oc_lldp_types_MANAGEMENT_ADDRESS 542785689
#define oc_lldp_types_CHASSIS_COMPONENT 0

#ifdef __cplusplus
}
#endif

#endif
