/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-routing-policy.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_ROUTING_POLICY_H_
#define _OPENCONFIG_ROUTING_POLICY_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_rpol__ns
#define oc_rpol__ns 277214873
#define oc_rpol__ns_id "http://openconfig.net/yang/routing-policy"
#define oc_rpol__ns_uri "http://openconfig.net/yang/routing-policy"
#endif

#define oc_rpol_prefix 1408440115
#define oc_rpol_tag 21925559
#define oc_rpol_set_tag 177790014
#define oc_rpol_conditions 975488036
#define oc_rpol_prefix_set 1234120084
#define oc_rpol_INLINE 0
#define oc_rpol_match_prefix_set 499359715
#define oc_rpol_name 1998270519
#define oc_rpol_ACCEPT_ROUTE 0
#define oc_rpol_defined_sets 952897476
#define oc_rpol_interface 221572658
#define oc_rpol_tag_value 633774587
#define oc_rpol_mode 575893728
#define oc_rpol_routing_policy 1803236680
#define oc_rpol_REFERENCE 1
#define oc_rpol_ip_prefix 289539202
#define oc_rpol_match_interface 1869116648
#define oc_rpol_match_set_options 517327943
#define oc_rpol_prefix_sets 2035865838
#define oc_rpol_config 2105663071
#define oc_rpol_MIXED 2
#define oc_rpol_statements 1505610507
#define oc_rpol_policy_result 1672578308
#define oc_rpol_call_policy 1718898824
#define oc_rpol_subinterface 1294223328
#define oc_rpol_state 630973766
#define oc_rpol_statement 2020184598
#define oc_rpol_IPV6 1
#define oc_rpol_policy_definition 927599493
#define oc_rpol_inline 1987224790
#define oc_rpol_address 1266954393
#define oc_rpol_REJECT_ROUTE 1
#define oc_rpol_neighbor_set 1237696180
#define oc_rpol_neighbor_sets 477381007
#define oc_rpol_IPV4 0
#define oc_rpol_tag_set 196489743
#define oc_rpol_match_neighbor_set 2124471048
#define oc_rpol_prefixes 1405994391
#define oc_rpol_match_tag_set 2016437036
#define oc_rpol_reference 1577200258
#define oc_rpol_masklength_range 497977763
#define oc_rpol_install_protocol_eq 1943059095
#define oc_rpol_actions 2034878685
#define oc_rpol_policy_definitions 492676988
#define oc_rpol_tag_sets 381894197

#ifdef __cplusplus
}
#endif

#endif
