/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: vlan.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _VLAN_H_
#define _VLAN_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef sv__ns
#define sv__ns 221995028
#define sv__ns_id "http://sssup.it/yang/vlan"
#define sv__ns_uri "http://sssup.it/yang/vlan"
#endif

#define sv_vlan 71481437
#define sv_tagged_members 1787103177
#define sv_ACTIVE 0
#define sv_untagged_members 1440202410
#define sv_switched_vlans 1481044406
#define sv_SUSPENDED 1
#define sv_vlan_name 706279704
#define sv_vlan_status 509590750
#define sv_vlan_id 1443431623
#define sv_port_id 411479338
#define sv_member 387693123

#ifdef __cplusplus
}
#endif

#endif
